'use strict';

module.exports = [
    '/payment/main',
    '/payment/input',
    '/payment/top-ups',
    '/payment/reviews',
    '/payment/disputes',
    '/payment/payouts',
    '/payment/all-transactions',
    '/payment/subscriptions',
    '/payment/subscriptions/input',
    '/payment/quotes',
    '/payment/invoices',
    '/payment/collected-fees',
    '/balances/overview',
    '/balances/top-up',
    '/balances/payouts',
    '/balances/transfers',
    '/setting/account ',
    '/products/main',
    '/products/input',
    '/products/input/:id',
    '/products/coupons',
    '/products/coupons/input',
    '/products/detail/:id',
    '/products/paymentLinks',
    '/products/shipping-rates',
    '/products/tax-rates',
    '/issuing/main',
    '/issuing/authorizations',
    '/issuing/cardholders',
    '/issuing/disputes',
    '/issuing/transactions',
    '/issuing/new-card',
    '/customers/main',
    '/customers/edit/:id',
]